FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS pruner
COPY . .
RUN bunx turbo prune worker --docker

FROM base AS installer
WORKDIR /app
ENV NODE_ENV=production

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN bun run db:generate
RUN bun run build:worker

RUN rm -rf node_modules && \
    bun install --production --frozen-lockfile

FROM oven/bun:1-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/apps/worker/dist ./apps/worker/dist
COPY --from=installer /app/apps/worker/package.json ./apps/worker/package.json

CMD ["bun", "--no-env-file", "./apps/worker/dist/index.js"]