FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json 
COPY ./turbo.json ./turbo.json



COPY ./apps/web ./apps/web

# ENV DATABASE_URL=$DATABASE_URL



RUN bun install
RUN bun run db:generate
RUN echo "DATABASE_URL=$DATABASE_URL" > .env.local
RUN cat .env.local
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]