FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS pruner
COPY . .
RUN bunx turbo prune web --docker

FROM base AS installer
WORKDIR /app

ARG APP_NAME
ENV APP_NAME=${APP_NAME}

ARG HTTP_SERVER_URL
ENV HTTP_SERVER_URL=${HTTP_SERVER_URL}

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN bun run build:web

FROM oven/bun:1-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer /app/apps/web/public ./apps/web/public

EXPOSE 3000
CMD ["bun", "run", "apps/web/server.js"]