FROM oven/bun:1

WORKDIR /usr/src/app


COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json 
COPY ./turbo.json ./turbo.json



COPY ./apps/web ./apps/web

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ARG HTTP_SERVER_URL
ENV HTTP_SERVER_URL=$HTTP_SERVER_URL

RUN bun install
RUN bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]
