export const PLAN_LIMITS = {
  STARTER: {
    price: 0,
    workspaces: 1,
    members: 10,
    generationJobs: 30,
    campaigns: 600,
    apiKeys: 20,
    smtpAccounts: 5,
    mailSentDaily: 50,
    workspaceMailSentDaily: 50,
  },
  PROFESSIONAL: {
    price: 20,
    workspaces: 4,
    members: 30,
    generationJobs: 300,
    campaigns: 300,
    apiKeys: 50,
    smtpAccounts: 20,
    mailSentDaily: 200,
  },
  ULTRA: {
    price: 40,
    workspaces: 20,
    members: 100,
    generationJobs: 5000,
    campaigns: 200,
    apiKeys: 200,
    smtpAccounts: 100,
    mailSentDaily: 500,
  },
} as const;