version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: coldMailAndOutrech
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  http-server:
    build:
      context: .
      dockerfile: apps/http-server/Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/coldMailAndOutrech
        HTTP_PORT: 4000
        JWT_ACCESS_SECRET: "eb3a8f02b887b7953a4d4526e439216f6c15127770a2b156f7c96d5e17745130"
        JWT_REFRESH_SECRET: "09484913e34be8eedb7ee2b2b7cf8f1f78d248e3caa1203a68ab8ce3ff5cf82c"

    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/coldMailAndOutrech
      HTTP_PORT: 4000
      JWT_ACCESS_SECRET: "eb3a8f02b887b7953a4d4526e439216f6c15127770a2b156f7c96d5e17745130"
      JWT_REFRESH_SECRET: "09484913e34be8eedb7ee2b2b7cf8f1f78d248e3caa1203a68ab8ce3ff5cf82c"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/coldMailAndOutrech

    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres:5432/coldMailAndOutrech

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "3000:3000"