# Base Stage
FROM oven/bun:1 AS base

WORKDIR /app


# Pruner Stage
FROM base AS pruner

COPY . .

RUN bunx turbo prune http-server --docker


# Installer Stage
FROM base AS installer

WORKDIR /app

# IMPORTANT: build environment
ENV NODE_ENV=production

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN bun run db:generate

RUN bun run build:http


# Runner Stage
FROM oven/bun:1 AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=installer /app .

EXPOSE 4000

CMD ["bun", "run", "start:http"]