FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
ARG PORT

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json 
COPY ./turbo.json ./turbo.json



COPY ./apps/http-server ./apps/http-server

ENV DATABASE_URL=$DATABASE_URL
ENV PORT=$PORT



RUN bun install
RUN bun run build

EXPOSE 4000

CMD [ "bun", "run", "start:http" ]