FROM oven/bun:1 AS base
WORKDIR /app

FROM base AS pruner
COPY . .
RUN bunx turbo prune http-server --docker

FROM base AS installer
WORKDIR /app
ENV NODE_ENV=production

COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/bun.lock ./bun.lock

RUN --mount=type=cache,target=/root/.bun/install/cache \
    bun install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN bun run db:generate
RUN bun run build:http

# Production Prune (removes unnecessary dev dependencies/cache)
RUN rm -rf node_modules && \
    bun install --production --frozen-lockfile

FROM oven/bun:1-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy only runtime dependencies and built dist output
COPY --from=installer /app/node_modules ./node_modules
COPY --from=installer /app/apps/http-server/dist ./apps/http-server/dist
COPY --from=installer /app/apps/http-server/package.json ./apps/http-server/package.json

EXPOSE 4000
CMD ["bun", "--no-env-file", "./apps/http-server/dist/index.js"]