name: Development CI

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test and Build
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        env:
          BUN_INSTALL_CACHE_DIR: ${{ runner.temp }}/bun-cache
        run: |
          rm -rf "$BUN_INSTALL_CACHE_DIR"
          mkdir -p "$BUN_INSTALL_CACHE_DIR"
          bun install --frozen-lockfile


       #only build images for testing
      - name: Build HTTP image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/http-server/Dockerfile.http
          push: false

      - name: Build Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/worker/Dockerfile.worker
          push: false

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile.web
          push: false
          build-args: |
           APP_NAME=Cold Out Reach
           HTTP_SERVER_URL=http://http-server:4000/api/v1/